apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhav-io
  labels:
    app: bhav-io
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bhav-io
  template:
    metadata:
      labels:
        app: bhav-io
    spec:
      containers:
        - name: bhav-io
          image: registry.k8s.bhav.io/heatsheet/heatsheet:#RELEASE_VERSION
