name: Build

on:
  pull_request:
    branches: [ main ]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -f- app/