name: Build

on:
  pull_request:
    branches: [ main ]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: registry.k8s.bhav.io
          username: bhav
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build image
        run: |
          docker build app -t registry.k8s.bhav.io/heatsheet/heatsheet:v1.0.0
          docker push registry.k8s.bhav.io/heatsheet/heatsheet:v1.0.0
          

      - name: Ready Deployment YAML
        run: |
          sed -i 's/#WEB_USERNAME/${{ secrets.WEB_USERNAME }}/g' ./k8s/deploy.yaml
          sed -i 's/#WEB_PASSWORD/${{ secrets.WEB_PASSWORD }}/g' ./k8s/deploy.yaml
          sed -i 's/#TADO_USERNAME/${{ secrets.TADO_USERNAME }}/g' ./k8s/deploy.yaml
          sed -i 's/#TADO_PASSWORD/${{ secrets.TADO_PASSWORD }}/g' ./k8s/deploy.yaml
          sed -i 's/#INFLUXDB_BUCKET/${{ secrets.INFLUXDB_BUCKET }}/g' ./k8s/deploy.yaml
          sed -i 's/#INFLUXDB_TOKEN/${{ secrets.INFLUXDB_TOKEN }}/g' ./k8s/deploy.yaml
          sed -i 's/#INFLUXDB_ORG/${{ secrets.INFLUXDB_ORG }}/g' ./k8s/deploy.yaml
          sed -i 's/#INFLUXDB_ENABLED/${{ secrets.INFLUXDB_ENABLED }}/g' ./k8s/deploy.yaml
          sed -i 's/#INFLUXDB_URL/${{ secrets.INFLUXDB_URL }}/g' ./k8s/deploy.yaml


      - uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: https://144.21.63.54:16443
          k8s-secret: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET }}

      - uses: azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
            ./k8s/deploy.yaml
          images: |
            registry.k8s.bhav.io/heatsheet/heatsheet:v1.0.0